### ISSUE TITLE
# of params for the small model

### ISSUE THREAD

**Issue by jnhwkim** [MILVLG/mcan-vqa#12]
Your small model (6-Layer) has 57,812,491 parameters. However, the paper reports 56M for it (Table 1b). What does bring this dicrepancy?
```
p=0
for k,v in data['state_dict'].items():
    p+=functools.reduce(operator.mul, v.size(), 1)
>>> p
57812491
```

**Comment by yuzcccc** [comment]
This difference is caused by different sizes of question token vocabulary. Here we calculate vocab from all splits, while in the results in Table 1b, the vocab is calculated on the train split. This makes the model size in the paper a little bit smaller.

**Comment by jnhwkim** [comment]
Thanks! :-)
