### ISSUE TITLE
Code for learned image and question attentions

### ISSUE THREAD

**Issue by Karol-G** [MILVLG/mcan-vqa#19]
Hey,

in your paper you showed some examples of learned image and question attentions (Figure 8).
I want to replicate these examples if possible. 
Can you post the code you used to extract and create the learned image and question attentions?

Best,
Karol

**Comment by clytze0216** [comment]
@Karol-G
Hi!
Did you succeed replicating the image and question attentions?I want to relicate this examples in Figure8 and 7. If you succeed,could you kindly share the code with me?I am very new to this field ,so I'm very sorry to disturb you . Looking forward to your reply :)

 Best
 Z

**Comment by Karol-G** [comment]
Hi,

I actually don't remember if I was able to replicate them. However, after this i created a library a while ago that is able to extract grad-cam saliency/attention maps for most models in just a few lines of code. https://github.com/MECLabTUDA/M3d-Cam
I don't know if it is compatible with VQA too though, but you can try if you want.

Best
Karol
