### ISSUE TITLE
pretrained frcnn and network

### ISSUE THREAD

**Issue by nithinraok** [MILVLG/mcan-vqa#2]
Hi, Thanks for your project and great work.
I am looking to run it on new images but using other pretrained faster-rcnn features like COCO giving wrong answer. Can you please provide pretrained faster-rcnn model and network to replicate. 

Thanks

**Comment by MIL-VLG** [comment]
hi，the pre-trained Faster RCNN model are provided at [here](https://github.com/peteanderson80/bottom-up-attention). We use the model with K\in[10,100] to extract visual features from the image.

**Comment by nithinraok** [comment]
Thanks for your swift response. I was guessing you used other pytorch model instead of caffe to get Visual Genome features.
