### ISSUE TITLE
question about answer processing

### ISSUE THREAD

**Issue by muaz1994** [MILVLG/mcan-vqa#23]
Hi. thanks for your code.
May I please ask, in the case where multiple questions for the same image are given, why are you assigning a label <1 for each question, as in:
```
def get_score(occur):
    if occur == 0:
        return .0
    elif occur == 1:
        return .3
    elif occur == 2:
        return .6
    elif occur == 3:
        return .9
    else:
        return 1.
```
Why not assign 1 to each and treat it individually? Is it to avoid confusion in predicting the answer at test time?

**Comment by MIL-VLG** [comment]
This is to model the answering confidence during training. Besides, this strategy is borrowed from the implementation of [BAN](https://github.com/jnhwkim/ban-vqa)

**Comment by muaz1994** [comment]
Thanks!
