### ISSUE TITLE
log file

### ISSUE THREAD

**Issue by muaz1994** [MILVLG/mcan-vqa#25]
Hello and thanks for your code.
May you please share your log file for validation split (`results/log/log_run_small.txt`)? I am doing some minor changes in your code, and therefore it would be helpful to compare each epoch. The results are strange. Some minor changes I did degraded the accuracy. It started at 48% reached 60% at the 9th epoch. I don't assume it will reach 67% in a few more epochs, as it increases very slowly. 

Thanks

**Comment by MIL-VLG** [comment]
You can run a `mcan-small` model by yourself checking out an unmodified version of this repo : )
