### ISSUE TITLE
net.train() not called again after evaluation finishes

### ISSUE THREAD

**Issue by fawazsammani** [MILVLG/mcan-vqa#26]
Hi!

From your code, I realized that after you run the `eval` function and start the next training epoch, you do not turn back to training mode by `net.train()`, as `net.train()` is called before the epoch loop. Shouldn't that affect since you are using dropout?

**Comment by MIL-VLG** [comment]
In `eval()`, we use the saved model weights to initialize a new net for each call. That is to say, it would not affect the status of the net for training.

**Comment by fawazsammani** [comment]
Sorry, didn't notice this.
