### ISSUE TITLE
the problem about result jons file

### ISSUE THREAD

**Issue by 1055032529** [MILVLG/mcan-vqa#28]
Hi,thank for your opening code and excellent work.
i have a problem when i upload the json file which is the ans to the test2015 to the EVA AI it gets false and the error info as fellow:

'Results do not correspond to current VQA set. Either the results do have predictions for all question ids in annotation file or there is one/more questions id that does not belong to the question ids in the annotation file.'

Have you met the problem before?

**Comment by MIL-VLG** [comment]
No, we haven't met this problem before. What is the file size of your json file? It should be 20MB roughly. By the way, could it be the networking problem that you do not successfully submit the complete file to the server?

**Comment by 1055032529** [comment]
> No, we haven't met this problem before. What is the file size of your json file? It should be 20MB roughly. By the way, could it be the networking problem that you do not successfully submit the complete file to the server?

yes,the size of my json file is about 20MB , May be you are right, i dont sure that the server is still supporting right now, it is unfamiliar to me.Thank you, i will try more times
