### ISSUE TITLE
VQA CPv2

### ISSUE THREAD

**Issue by zizheng777** [MILVLG/mcan-vqa#29]
你好，我想问一下MCAN有在VQA CPv2上测试过性能吗？

**Comment by MIL-VLG** [comment]
We have not yet. I have seen some other papers report the MCAN results on VQA-CP. However, I forget their paper name and  you can find it yourself.

**Comment by ghost** [comment]
> 你好，我想问一下MCAN有在VQA CPv2上测试过性能吗？

请问您找到了吗？
