### ISSUE TITLE
Visualizations of the learned attention maps

### ISSUE THREAD

**Issue by clytze0216** [MILVLG/mcan-vqa#32]
Hi! MCAN team
  Thanks for your sharing

I want to replicate the visualization of the learned attention maps in Figure7
Can you post the code you used to extract and create the learned attention maps?
 Looking forward to your reply ! 

 Best

**Comment by MIL-VLG** [comment]
Sorry that the student who wrote the visualization code said that he has lost it. But the visualization is obtained using `matplotlib`. I think you can write it by yourself.
