### ISSUE TITLE
Features' file loading in the code

### ISSUE THREAD

**Issue by ifmaq1** [MILVLG/mcan-vqa#36]
Hi, 
I am confused regarding how you tackled the "**bbox**" information in the code. I can see loading the image features **x** from ".**npz**" file only.

Also, it is mentioned that we can work with grid features as well. Grid features' file with ".**pth**" extension only contains features/weights with tensor size **[1, 2048, 19, 29]**(a sample feature file)  and not any bounding box information, object detection etc. Then how can we cater those features without any such information.

**Comment by MIL-VLG** [comment]
The bbox information is an optional feature in this repo, our models do not use this by default.
