### ISSUE TITLE
single question test

### ISSUE THREAD

**Issue by miao404** [MILVLG/mcan-vqa#38]
I am trying to do a single question test, so I reduce the test_question.json to one picture and one question, and I encounter this problem:
`RuntimeError: Error(s) in loading state_dict for Net:
        size mismatch for embedding.weight: copying a param with shape torch.Size([20572, 300]) from checkpoint, the shape in current model is torch.Size([18405, 300]).`

Do you know how to fix this ? or the test_question.json is just stable which I cannot modify  the scale of the pictures and the questions?

Can you give me some suggestions about how to test single question in single picture ?

Thanks a lot.

**Comment by MIL-VLG** [comment]
This may be due to the vocabulary size for the question. Have you changed the config for the training vocab (or split)?

**Comment by GaoKangYu** [comment]
> This may be due to the vocabulary size for the question. Have you changed the config for the training vocab (or split)?

I met the same problem, how can I test single question in single picture ? 

Whitch .py file and how to  changed the config for the training vocab (or split) ? 

Thanks a lot.

**Comment by MIL-VLG** [comment]
This repo does not support such single image testing.
