### ISSUE TITLE
Can I run code with CPU?

### ISSUE THREAD

**Issue by msg67** [MILVLG/mcan-vqa#40]
Hello and thanks for your code and share
When I tried to run your work, couldn't download SPACY==2.1.0, so I run it with SPACY==3.2.3 (last version), and thus I have to change the pipeline, from ‘‘en_vectors_web_lg-2.1.0” to “en_core_web_lg-3.2.0”, after that I change ‘‘ yaml_dict = yaml.safe_load(f)’’ that was "yaml_dict = yaml.load(f)" before.
And in the end, I face this error:  “AssertionError: Torch not compiled with CUDA enabled”.
I tried with: ...GPU=="CPU” but it doesn't work either.
Please guide me, how to run with CPU (my GPU that doesn't support CUDA requirements), if possible.

**Comment by MIL-VLG** [comment]
It is possible but we do not provide an implementation for that, since it is too slow to train the model. If you want to do that, you can modify the code in exec.py with `cuda` lines.
