### ISSUE TITLE
About initialize the GloVe

### ISSUE THREAD

**Issue by DLrook** [MILVLG/mcan-vqa#46]
Hello and thank you for your code and share ,
When I execute wget https://github.com/explosion/spacy-models/releases/download/en_vectors_web_lg-2.1.0/en_vectors_web_lg-2.1.0.tar.gz -O en_ vectors_web_lg-2.1.0.tar.gz command, I found that the web page doesn't exist, please guide me what I should do!

**Comment by MIL-VLG** [comment]
I can successfully download the url `https://github.com/explosion/spacy-models/releases/download/en_vectors_web_lg-2.1.0/en_vectors_web_lg-2.1.0.tar.gz` manually. Maybe you need some proxy?
